// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"mall/user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				//用户注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: UserRegister(serverCtx),
			},
			{
				//用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: UserLogin(serverCtx),
			},
			{
				//获取商品信息
				Method:  http.MethodPost,
				Path:    "/getGoodsInfo",
				Handler: GetGoodsInfo(serverCtx),
			},
			{
				//获取商品信息
				Method:  http.MethodGet,
				Path:    "/testPushMq",
				Handler: TestPushMq(serverCtx),
			},
		},
	)
}
