// Code generated by goctl. DO NOT EDIT.
// Source: goods.proto

package server

import (
	"context"

	"mall/goods/internal/logic"
	"mall/goods/internal/svc"
	"mall/goods/pb/goods"
)

type GoodsServer struct {
	svcCtx *svc.ServiceContext
	goods.UnimplementedGoodsServer
}

func NewGoodsServer(svcCtx *svc.ServiceContext) *GoodsServer {
	return &GoodsServer{
		svcCtx: svcCtx,
	}
}

func (s *GoodsServer) GetGoodsInfo(ctx context.Context, in *goods.Request) (*goods.Response, error) {
	l := logic.NewGetGoodsInfoLogic(ctx, s.svcCtx)
	return l.GetGoodsInfo(in)
}
