// Code generated by goctl. DO NOT EDIT.

package msgmodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	messageFieldNames          = builder.RawFieldNames(&Message{})
	messageRows                = strings.Join(messageFieldNames, ",")
	messageRowsExpectAutoSet   = strings.Join(stringx.Remove(messageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	messageRowsWithPlaceHolder = strings.Join(stringx.Remove(messageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	messageModel interface {
		Insert(ctx context.Context, data *Message) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Message, error)
		FindList(ctx context.Context) (*[]Message, error)
		Update(ctx context.Context, data *Message) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMessageModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Message struct {
		Id       int64     `db:"id"`
		MsgType  int       `db:"msg_type"`  // 信息类型 1-邮箱 2-短信
		SceneNo  string    `db:"scene_no"`  // 场景码
		UserName string    `db:"user_name"` // 接收人用户名
		Phone    string    `db:"phone"`     // 接收人手机号码
		Email    string    `db:"email"`     // 接收人邮箱
		Title    string    `db:"title"`     // 标题
		Content  string    `db:"content"`   // 发送内容
		Status   int       `db:"status"`    // 发送状态 0-待发送 1-发送成功 2-发送失败 3-发送中
		CreateAt time.Time `db:"create_at"`
		UpdateAt time.Time `db:"update_at"`
	}
)

func newMessageModel(conn sqlx.SqlConn) *defaultMessageModel {
	return &defaultMessageModel{
		conn:  conn,
		table: "`message`",
	}
}

func (m *defaultMessageModel) withSession(session sqlx.Session) *defaultMessageModel {
	return &defaultMessageModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`message`",
	}
}

func (m *defaultMessageModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMessageModel) FindOne(ctx context.Context, id int64) (*Message, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", messageRows, m.table)
	var resp Message
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessageModel) FindList(ctx context.Context) (*[]Message, error) {
	query := fmt.Sprintf("select %s from %s where `status` = 0 limit 100", messageRows, m.table)
	var resp []Message
	err := m.conn.QueryRowsCtx(ctx, &resp, query)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, nil
	default:
		return nil, err
	}
}

func (m *defaultMessageModel) Insert(ctx context.Context, data *Message) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, messageRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.MsgType, data.SceneNo, data.UserName, data.Phone, data.Email, data.Title, data.Content, data.Status)
	return ret, err
}

func (m *defaultMessageModel) Update(ctx context.Context, data *Message) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, messageRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.MsgType, data.SceneNo, data.UserName, data.Phone, data.Email, data.Title, data.Content, data.Status, data.Id)
	return err
}

func (m *defaultMessageModel) tableName() string {
	return m.table
}
