// Code generated by goctl. DO NOT EDIT.
// Source: proto.proto

package msgclient

import (
	"context"

	"mall/msg/proto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = proto.SendRequest
	Response = proto.SendResponse

	Msg interface {
		SendMsg(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultMsg struct {
		cli zrpc.Client
	}
)

func NewMsg(cli zrpc.Client) Msg {
	return &defaultMsg{
		cli: cli,
	}
}

func (m *defaultMsg) SendMsg(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := proto.NewMsgClient(m.cli.Conn())
	return client.SendMsg(ctx, in, opts...)
}
