// Code generated by goctl. DO NOT EDIT.
package types

type UserRegisterRequest struct {
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`
	Password string `json:"password"`
}

type UserLoginRequest struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type GetGoodsInfoRequest struct {
	GoodsId string `json:"goodsId"`
}

type Response struct {
	Base
	Data interface{} `json:"data"`
}
