// Code generated by goctl. DO NOT EDIT.
// Source: msg.proto

package server

import (
	"context"

	"mall/msg/internal/logic"
	"mall/msg/internal/svc"
	"mall/msg/proto"
)

type MsgServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedMsgServer
}

func NewMsgServer(svcCtx *svc.ServiceContext) *MsgServer {
	return &MsgServer{
		svcCtx: svcCtx,
	}
}

func (s *MsgServer) SendMsg(ctx context.Context, in *proto.SendRequest) (*proto.SendResponse, error) {
	l := logic.NewSendMsgLogic(ctx, s.svcCtx)
	return l.SendMsg(in)
}
